AllCops:
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
